# Generated by Django 3.2.7 on 2021-10-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotifyAPI', '0002_auto_20211009_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='user',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
