# Generated by Django 3.2.7 on 2021-10-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('contents', models.CharField(max_length=500)),
                ('user_id', models.CharField(max_length=300)),
            ],
        ),
    ]
