# Generated by Django 3.2.7 on 2021-10-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=300)),
                ('content_id', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('progress', models.CharField(max_length=300)),
            ],
        ),
    ]
