# Generated by Django 3.2.7 on 2021-10-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
