# Generated by Django 3.2.7 on 2021-10-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_auto_20211026_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=300)),
                ('content_id', models.CharField(max_length=300)),
                ('comments', models.CharField(max_length=300, null=True)),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultimediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('external_id', models.CharField(max_length=300, unique=True)),
                ('total_ratio', models.IntegerField(null=True)),
                ('comments', models.TextField(null=True)),
            ],
        ),
    ]
