# Generated by Django 3.2.7 on 2021-10-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_comment_multimediacontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimediacontent',
            old_name='total_ratio',
            new_name='total_rating',
        ),
        migrations.AddField(
            model_name='multimediacontent',
            name='type',
            field=models.CharField(default='song', max_length=50),
            preserve_default=False,
        ),
    ]
