# Generated by Django 3.2.7 on 2021-11-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_auto_20211031_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='progress',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='state',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
