# Generated by Django 3.2.7 on 2021-11-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_auto_20211101_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediacontent',
            name='total_rating',
            field=models.FloatField(null=True),
        ),
    ]
