# Generated by Django 3.2.7 on 2021-11-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_auto_20211101_2147'),
        ('Api', '0010_alter_multimediacontent_total_rating'),
    ]

    operations = [
    ]
