# Generated by Django 3.2.7 on 2021-11-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_auto_20211104_1835'),
        ('Api', '0012_user_following'),
    ]

    operations = [
    ]
