# Generated by Django 3.2.7 on 2021-12-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0014_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.TextField(null=True),
        ),
    ]
